### ISSUE TITLE
Can't find the apk

### ISSUE THREAD

**Issue by Gr-Nobel** [ademar111190/goodreads#1]
Hey there!

I want to test the client. But there is no apk file to download.

**Comment by ademar111190** [comment]
@Gr-Nobel This project doesn't work anymore because Goodreads does not issue new developer keys: https://www.goodreads.com/api

There is no apk because you need to build your own with the API key https://github.com/ademar111190/goodreads/blob/master/app/src/main/res/values/config.xml#L5 but as I said it is not possible to get new API keys
